### ISSUE TITLE
How can i start this project?

### ISSUE THREAD

**Issue by ChangsoonKim** [lvgl/lv_port_stm32f429_disco#1]
Hello, I try to start with this project.

But I can not build this source using TrueStudio 9.2  or sw4stm32!

please help me

**Comment by embeddedt** [comment]
Hi,

What errors do you get when using SW4STM32?

**Comment by kisvegabor** [comment]
The project is already changed to CubeIDE.

I've updated the README. Sorry for the confusion.

**Comment by ChangsoonKim** [comment]
@kisvegabor Thank you! I will try to start with CubeIDE!

**Comment by ChangsoonKim** [comment]
@kisvegabor @embeddedt 
Hi I try to start project usgint CubeIDE! But I failed to start.

My working environment 
* windows 10 64bit
* CubeIDE 1.3.0
* Debug Mode

I find "Debug" configuration is missing in the CubeIDE and Release configure has Absolute path like that "-I"/home/kisvegabor/stm32_workspace_2/stm32_lvgl/inc" -I"/home/kisvegabor/stm32_workspace_2/stm32_lvgl/Utilities/STM32F429I-Discovery"" in Realease/src/subdir.mk.

I try to run this project again after change Include path! 






I find 2 point of my failer

**Comment by VictorTagayun** [comment]
Do you have the IOC file for this?

**Comment by kisvegabor** [comment]
No, we don't have an IOC file for this yet. :slightly_frowning_face: 
Bt it'd be great to have one. So if you are working on it contribution would be very welcome!
