### ISSUE TITLE
Screen corrupted upon program start

### ISSUE THREAD

**Issue by gidiguy** [lvgl/lv_port_stm32f429_disco#3]
Hello,

Trying this project on STM32F429i-disco board.

Project compiles without errors on STm32CubeIDE, but displays a corrupted main screen. Trying to touch different areas results in nothing. I think the process is hung somewhere.

The "standard" ST demo project loads and runs correctly, so I guess my hardware is OK.

Any ideas?

-Gideon
![IMG_7006](https://user-images.githubusercontent.com/12548865/90402606-62817400-e0a8-11ea-882c-13a45826ef40.jpg)

**Comment by papadkostas** [comment]
Please remove line 47 from main.c
https://github.com/lvgl/lv_port_stm32f429_disco/blob/master/src/main.c#L47

**Comment by embeddedt** [comment]
Not sure how that ended up there - I've removed the extra line in https://github.com/lvgl/lv_port_stm32f429_disco/commit/4ee7d4bf603fa7c7141281b0eb4a17ef54f34118. I'm not sure if two demos  would cause graphical artifacts, but the second line definitely doesn't belong.
