### ISSUE TITLE
Port to MBed Studio w/ MBed OS

### ISSUE THREAD

**Issue by pcotret** [lvgl/lv_port_stm32f429_disco#4]
Hi,
I'm trying to port this project to work with the MBed Studio IDE and MBedOS.
I have some issues with `tft_init` and `lcd_init` (undefined symbols during link...).
First steps:
- Created an Mbed Studio project w/ MBedOS 6.
- Importing the LVGL v7 library + `lv_conf.h` configuration
- Copying the [hal_stm_lvgl folder](https://github.com/lvgl/lv_port_stm32f429_disco/tree/master/hal_stm_lvgl) in my project.
- Including related headers in my `main.cpp`

Am I missing something ?

**Comment by embeddedt** [comment]
Add an `#error` statement to `hal_stm_lvgl/tft/tft.c` and check if compilation fails. If not, the IDE needs to have the source files added to its list.

**Comment by pcotret** [comment]
Compilation fails on my `#error` statement, which is rather good.
Otherwise:
```bash
Link: mbed-os-empty
[Warning] @0,0: L3912W: Option 'legacyalign' is deprecated.
[Error] @0,0: L6218E: Undefined symbol tft_init() (referred from BUILD/DISCO_F429ZI/ARMC6/main.o).
```
Need to understand how build profiles work in MBed Studio: it seems a library is missing during link.
